<?php
declare(strict_types = 1);

return [
    'application' => [
        'label'  => 'Applications',
        'labels' => [
            'name'                     => 'Applications',
            'singular_name'            => 'Application',
            'add_new'                  => 'Add New Application',
            'add_new_item'             => 'Add New Application',
            'edit_item'                => 'Edit Application',
            'new_item'                 => 'New Application',
            'view_item'                => 'View Application',
            'view_items'               => 'View Applications',
            'search_items'             => 'Search Applications',
            'not_found'                => 'No applications found',
            'not_found_in_trash'       => 'No applications found in Trash',
            'parent_item_colon'        => 'Parent Application:',
            'all_items'                => 'All Applications',
            'archives'                 => 'Application Archives',
            'attributes'               => 'Application Attributes',
            'insert_into_item'         => 'Insert into application',
            'uploaded_to_this_item'    => 'Uploaded to this application',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Applications',
            'filter_items_list'        => 'Filter applications list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Applications list navigation',
            'items_list'               => 'Applications list',
            'item_published'           => 'Application published.',
            'item_published_privately' => 'Application published privately.',
            'item_reverted_to_draft'   => 'Application reverted to draft.',
            'item_trashed'             => 'Application trashed.',
            'item_scheduled'           => 'Application scheduled.',
            'item_updated'             => 'Application updated.',
            'item_link'                => 'Application Link',
            'item_link_description'    => 'A link to a application.',
        ],
        'description'         => 'Frequently Asked Questions (Applications)',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 60,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['application', 'applications'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
        ],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],
];
