<?php
declare(strict_types = 1);

return [

    'mail_server' => [
        'label'  => 'Mail Servers',
        'labels' => [
            'name'                     => 'Mail Servers',
            'singular_name'            => 'Mail Server',
            'add_new'                  => 'Add New Mail Server',
            'add_new_item'             => 'Add New Mail Server',
            'edit_item'                => 'Edit Mail Server',
            'new_item'                 => 'New Mail Server',
            'view_item'                => 'View Mail Server',
            'view_items'               => 'View Mail Servers',
            'search_items'             => 'Search Mail Servers',
            'not_found'                => 'No mail servers found',
            'not_found_in_trash'       => 'No mail servers found in Trash',
            'parent_item_colon'        => 'Parent Mail Server:',
            'all_items'                => 'All Mail Servers',
            'archives'                 => 'Mail Server Archives',
            'attributes'               => 'Mail Server Attributes',
            'insert_into_item'         => 'Insert into mail server',
            'uploaded_to_this_item'    => 'Uploaded to this mail server',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Mail Servers',
            'filter_items_list'        => 'Filter mail servers list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Mail Servers list navigation',
            'items_list'               => 'Mail Servers list',
            'item_published'           => 'Mail Server published.',
            'item_published_privately' => 'Mail Server published privately.',
            'item_reverted_to_draft'   => 'Mail Server reverted to draft.',
            'item_trashed'             => 'Mail Server trashed.',
            'item_scheduled'           => 'Mail Server scheduled.',
            'item_updated'             => 'Mail Server updated.',
            'item_link'                => 'Mail Server Link',
            'item_link_description'    => 'A link to a mail server.',
        ],
        'description'         => 'Mail Servers',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => false,
        'show_in_nav_menus'   => false,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['mail_server', 'mail_servers'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
        ],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],
];
