<?php
declare(strict_types = 1);

return [

    // change post type from email_template to message_template
    'email_template' => [
        'label'  => 'Email Template',
        'labels' => [
            'name'                     => 'Email Templates',
            'singular_name'            => 'Email Template',
            'add_new'                  => 'Add New Email Template',
            'add_new_item'             => 'Add New Email Template',
            'edit_item'                => 'Edit Email Template',
            'new_item'                 => 'New Email Template',
            'view_item'                => 'View Email Template',
            'view_items'               => 'View Email Templates',
            'search_items'             => 'Search Email Templates',
            'not_found'                => 'No email templates found',
            'not_found_in_trash'       => 'No email templates found in Trash',
            'parent_item_colon'        => 'Parent Email Template:',
            'all_items'                => 'Email Templates',
            'archives'                 => 'Email Template Archives',
            'attributes'               => 'Email Template Attributes',
            'insert_into_item'         => 'Insert into email template',
            'uploaded_to_this_item'    => 'Uploaded to this email template',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Email Templates',
            'filter_items_list'        => 'Filter email templates list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Email Templates list navigation',
            'items_list'               => 'Email Templates list',
            'item_published'           => 'Email Template published.',
            'item_published_privately' => 'Email Template published privately.',
            'item_reverted_to_draft'   => 'Email Template reverted to draft.',
            'item_trashed'             => 'Email Template trashed.',
            'item_scheduled'           => 'Email Template scheduled.',
            'item_updated'             => 'Email Template updated.',
            'item_link'                => 'Email Template Link',
            'item_link_description'    => 'A link to a email template.',
        ],
        'description'         => 'Email Templates',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => false,
        'show_in_nav_menus'   => false,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'           => 'dashicons-id',
        'capability_type'     => ['email_template', 'email_templates'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => ['title',],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
            'with_front' => false,
        ],
        'can_export'       => true,
        'delete_with_user' => false,
    ],
];
