<?php
declare(strict_types = 1);

use NatOkpe\Wp\Plugin\KeekSetup\Engine;

/* Config: Post types */
return [

    // change post type from email_template to message_template
    'email_template' => [
        'label'  => 'Email Template',
        'labels' => [
            'name'                     => 'Email Templates',
            'singular_name'            => 'Email Template',
            'add_new'                  => 'Add New Email Template',
            'add_new_item'             => 'Add New Email Template',
            'edit_item'                => 'Edit Email Template',
            'new_item'                 => 'New Email Template',
            'view_item'                => 'View Email Template',
            'view_items'               => 'View Email Templates',
            'search_items'             => 'Search Email Templates',
            'not_found'                => 'No email templates found',
            'not_found_in_trash'       => 'No email templates found in Trash',
            'parent_item_colon'        => 'Parent Email Template:',
            'all_items'                => 'Email Templates',
            'archives'                 => 'Email Template Archives',
            'attributes'               => 'Email Template Attributes',
            'insert_into_item'         => 'Insert into email template',
            'uploaded_to_this_item'    => 'Uploaded to this email template',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Email Templates',
            'filter_items_list'        => 'Filter email templates list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Email Templates list navigation',
            'items_list'               => 'Email Templates list',
            'item_published'           => 'Email Template published.',
            'item_published_privately' => 'Email Template published privately.',
            'item_reverted_to_draft'   => 'Email Template reverted to draft.',
            'item_trashed'             => 'Email Template trashed.',
            'item_scheduled'           => 'Email Template scheduled.',
            'item_updated'             => 'Email Template updated.',
            'item_link'                => 'Email Template Link',
            'item_link_description'    => 'A link to a email template.',
        ],
        'description'         => 'Email Templates',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => false,
        'show_in_nav_menus'   => false,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'           => 'dashicons-id',
        'capability_type'     => ['email_template', 'email_templates'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => ['title',],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
            'with_front' => false,
        ],
        'can_export'       => true,
        'delete_with_user' => false,
    ],

    'mail_server' => [
        'label'  => 'Mail Servers',
        'labels' => [
            'name'                     => 'Mail Servers',
            'singular_name'            => 'Mail Server',
            'add_new'                  => 'Add New Mail Server',
            'add_new_item'             => 'Add New Mail Server',
            'edit_item'                => 'Edit Mail Server',
            'new_item'                 => 'New Mail Server',
            'view_item'                => 'View Mail Server',
            'view_items'               => 'View Mail Servers',
            'search_items'             => 'Search Mail Servers',
            'not_found'                => 'No mail servers found',
            'not_found_in_trash'       => 'No mail servers found in Trash',
            'parent_item_colon'        => 'Parent Mail Server:',
            'all_items'                => 'All Mail Servers',
            'archives'                 => 'Mail Server Archives',
            'attributes'               => 'Mail Server Attributes',
            'insert_into_item'         => 'Insert into mail server',
            'uploaded_to_this_item'    => 'Uploaded to this mail server',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Mail Servers',
            'filter_items_list'        => 'Filter mail servers list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Mail Servers list navigation',
            'items_list'               => 'Mail Servers list',
            'item_published'           => 'Mail Server published.',
            'item_published_privately' => 'Mail Server published privately.',
            'item_reverted_to_draft'   => 'Mail Server reverted to draft.',
            'item_trashed'             => 'Mail Server trashed.',
            'item_scheduled'           => 'Mail Server scheduled.',
            'item_updated'             => 'Mail Server updated.',
            'item_link'                => 'Mail Server Link',
            'item_link_description'    => 'A link to a mail server.',
        ],
        'description'         => 'Mail Servers',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => false,
        'show_in_nav_menus'   => false,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['mail_server', 'mail_servers'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
        ],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],

    'email_account' => [
        'label'  => 'Email Account',
        'labels' => [
            'name'                     => 'Email Accounts',
            'singular_name'            => 'Email Account',
            'add_new'                  => 'Add New Email Account',
            'add_new_item'             => 'Add New Email Account',
            'edit_item'                => 'Edit Email Account',
            'new_item'                 => 'New Email Account',
            'view_item'                => 'View Email Account',
            'view_items'               => 'View Email Accounts',
            'search_items'             => 'Search Email Accounts',
            'not_found'                => 'No email accounts found',
            'not_found_in_trash'       => 'No email accounts found in Trash',
            'parent_item_colon'        => 'Parent Email Account:',
            'all_items'                => 'Email Accounts',
            'archives'                 => 'Email Account Archives',
            'attributes'               => 'Email Account Attributes',
            'insert_into_item'         => 'Insert into email account',
            'uploaded_to_this_item'    => 'Uploaded to this email account',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Email Accounts',
            'filter_items_list'        => 'Filter email accounts list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Email Accounts list navigation',
            'items_list'               => 'Email Accounts list',
            'item_published'           => 'Email Account published.',
            'item_published_privately' => 'Email Account published privately.',
            'item_reverted_to_draft'   => 'Email Account reverted to draft.',
            'item_trashed'             => 'Email Account trashed.',
            'item_scheduled'           => 'Email Account scheduled.',
            'item_updated'             => 'Email Account updated.',
            'item_link'                => 'Email Account Link',
            'item_link_description'    => 'A link to a email account.',
        ],
        'description'         => 'Email Accounts',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => false,
        'show_in_nav_menus'   => false,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'           => 'dashicons-id',
        'capability_type'     => ['email_account', 'email_accounts'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => ['title'],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
            'with_front' => false,
        ],
        'can_export'       => true,
        'delete_with_user' => false,
    ],

    'faq' => [
        'label'  => 'FAQs',
        'labels' => [
            'name'                     => 'FAQs',
            'singular_name'            => 'FAQ',
            'add_new'                  => 'Add New FAQ',
            'add_new_item'             => 'Add New FAQ',
            'edit_item'                => 'Edit FAQ',
            'new_item'                 => 'New FAQ',
            'view_item'                => 'View FAQ',
            'view_items'               => 'View FAQs',
            'search_items'             => 'Search FAQs',
            'not_found'                => 'No faqs found',
            'not_found_in_trash'       => 'No faqs found in Trash',
            'parent_item_colon'        => 'Parent FAQ:',
            'all_items'                => 'All FAQs',
            'archives'                 => 'FAQ Archives',
            'attributes'               => 'FAQ Attributes',
            'insert_into_item'         => 'Insert into faq',
            'uploaded_to_this_item'    => 'Uploaded to this faq',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'FAQs',
            'filter_items_list'        => 'Filter faqs list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'FAQs list navigation',
            'items_list'               => 'FAQs list',
            'item_published'           => 'FAQ published.',
            'item_published_privately' => 'FAQ published privately.',
            'item_reverted_to_draft'   => 'FAQ reverted to draft.',
            'item_trashed'             => 'FAQ trashed.',
            'item_scheduled'           => 'FAQ scheduled.',
            'item_updated'             => 'FAQ updated.',
            'item_link'                => 'FAQ Link',
            'item_link_description'    => 'A link to a faq.',
        ],
        'description'         => 'Frequently Asked Questions (FAQs)',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['faq', 'faqs'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
            'editor',
            'trackbacks',
            'author',
            'excerpt',
            'page-attributes',
            'thumbnail',
        ],
        'taxonomies' => [
            'faq-topic'
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],

    'application' => [
        'label'  => 'Applications',
        'labels' => [
            'name'                     => 'Applications',
            'singular_name'            => 'Application',
            'add_new'                  => 'Add New Application',
            'add_new_item'             => 'Add New Application',
            'edit_item'                => 'Edit Application',
            'new_item'                 => 'New Application',
            'view_item'                => 'View Application',
            'view_items'               => 'View Applications',
            'search_items'             => 'Search Applications',
            'not_found'                => 'No applications found',
            'not_found_in_trash'       => 'No applications found in Trash',
            'parent_item_colon'        => 'Parent Application:',
            'all_items'                => 'All Applications',
            'archives'                 => 'Application Archives',
            'attributes'               => 'Application Attributes',
            'insert_into_item'         => 'Insert into application',
            'uploaded_to_this_item'    => 'Uploaded to this application',
            'featured_image'           => 'Featured image',
            'set_featured_image'       => 'Set featured image',
            'remove_featured_image'    => 'Remove featured image',
            'use_featured_image'       => 'Use as featured image',
            'menu_name'                => 'Applications',
            'filter_items_list'        => 'Filter applications list',
            'filter_by_date'           => 'Filter by date',
            'items_list_navigation'    => 'Applications list navigation',
            'items_list'               => 'Applications list',
            'item_published'           => 'Application published.',
            'item_published_privately' => 'Application published privately.',
            'item_reverted_to_draft'   => 'Application reverted to draft.',
            'item_trashed'             => 'Application trashed.',
            'item_scheduled'           => 'Application scheduled.',
            'item_updated'             => 'Application updated.',
            'item_link'                => 'Application Link',
            'item_link_description'    => 'A link to a application.',
        ],
        'description'         => 'Frequently Asked Questions (Applications)',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => false,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => false,
        'show_in_rest'        => true,
        'menu_position'       => 60,
        'menu_icon'        => 'dashicons-editor-help',
        'capability_type'     => ['application', 'applications'],
        // 'capabilities'     => [],
        'map_meta_cap'        => true,
        'supports'            => [
            'title',
        ],
        'taxonomies' => [
        ],
        'has_archive' => false,
        'rewrite' => [
        //     'slug' => '',
            'with_front' => false,
        ],
        // 'query_var'        => '',
        'can_export'       => true,
        'delete_with_user' => false,
    ],
];
